### ISSUE TITLE
loadinternal: cannot find runtime/cgo

### ISSUE THREAD

**Issue by umarcor** [docker/binfmt#18]
I'm trying to make and test this project in Travis CI with the following `.travis.yml`:

``` yaml
os: linux
services: docker
language: minimal
install: skip
script:
  - make clean
  - make
  - make test
```

The build (`go-compile.sh`) is showing `loadinternal: cannot find runtime/cgo`. Then, the test fails with `Cannot write to /proc/sys/fs/binfmt_misc/register: write /proc/sys/fs/binfmt_misc/register: invalid argument`. See https://travis-ci.com/dbhi/qus/builds/122668410#L2504-L2506 and https://travis-ci.com/dbhi/qus/builds/122668410#L2537.
